name: flutter_app
description: "Personal AI assistant mobile client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^5.4.4
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  drift: ^2.15.0
  drift_sqflite: ^2.0.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.5.0
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  grpc: ^3.2.4
  http: ^1.2.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  crypto: ^3.0.3
  path: ^1.9.0
  speech_to_text: ^6.5.0
  sqflite: ^2.3.3+1
  sqlite3_flutter_libs: ^0.5.22
  workmanager: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.18.0
  fake_cloud_firestore: ^3.1.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.5
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
